import { SliderProps, InputNumberProps, SwitchProps, TextAreaProps, CheckboxGroupProps, TreeSelectProps } from '@arco-design/web-react';
import { ImageUploaderProps } from './ImageUploader';
import { UploadFieldProps } from './UploadField';
import { SelectProps } from './Select';
import { RadioGroupProps } from './RadioGroup';
import enhancer from './enhancer';
import { InputProps } from './Input';
import { InputWithUnitProps } from './InputWithUnit';
import { EditTabProps } from './EditTab';
import { EditGridTabProps } from './EditGridTab';
import { InlineTextProps } from './InlineTextField';
import { AutoCompleteProps } from './AutoComplete';
import { InputSearchProps } from '@arco-design/web-react/es/Input';
import { ColorPickerField } from './ColorPickerField';
export { RichTextField } from './RichTextField';
export declare const TextField: (props: import("./enhancer").EnhancerProps & Omit<InputProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const InputWithUnitField: (props: import("./enhancer").EnhancerProps & Omit<InputWithUnitProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const SearchField: (props: import("./enhancer").EnhancerProps & Omit<InputSearchProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const TextAreaField: (props: import("./enhancer").EnhancerProps & Omit<TextAreaProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const NumberField: (props: import("./enhancer").EnhancerProps & Omit<InputNumberProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const SliderField: (props: import("./enhancer").EnhancerProps & Omit<SliderProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const UploadField: (props: import("./enhancer").EnhancerProps & Omit<UploadFieldProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const ImageUploaderField: (props: import("./enhancer").EnhancerProps & Omit<ImageUploaderProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const SelectField: (props: import("./enhancer").EnhancerProps & Omit<SelectProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const TreeSelectField: (props: import("./enhancer").EnhancerProps & Omit<TreeSelectProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const AutoCompleteField: (props: import("./enhancer").EnhancerProps & Omit<AutoCompleteProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const RadioGroupField: (props: import("./enhancer").EnhancerProps & Omit<RadioGroupProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const SwitchField: (props: import("./enhancer").EnhancerProps & Omit<SwitchProps, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const CheckboxField: (props: import("./enhancer").EnhancerProps & Omit<CheckboxGroupProps<any>, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const EditTabField: (props: import("./enhancer").EnhancerProps & Omit<EditTabProps<any>, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const EditGridTabField: (props: import("./enhancer").EnhancerProps & Omit<EditGridTabProps<any>, "value" | "onChange" | "mutators">) => JSX.Element;
export declare const InlineTextField: (props: import("./enhancer").EnhancerProps & Omit<InlineTextProps, "value" | "onChange" | "mutators">) => JSX.Element;
export { ColorPickerField };
export { enhancer };
